---
title: "Report"
author: "Silvia Ferrer y Ignacio Lloret"
date: "2023-11-27"
output: html_document
---

```{r setup, include=FALSE}

library(readr)
library(tidyverse)
library(DataExplorer)

df1 <- read.csv("../data/data2.txt")

df1 %>% glimpse

```
## Missing data

```{r, missing_data, fig.height=1.5}

plot_missing(df1, missing_only = TRUE, group = list("Low" = 0.05, "Medium"=0.25, "High"=0.5, "Very High" =1), geom_label_args = list("size" = 2))

```
## Categorical values

```{r, categorical_plot}
df1$SeniorCitizen <- df1$SeniorCitizen %>% as.factor()

cat_keep <- names(df1)[sapply(df1, function(x) is.character(x))]
numeric_columns <-  names(df1)[sapply(df1, function(x) is.numeric(x))]


df1[cat_keep] <- lapply(df1[cat_keep], as.factor) ## Create Factors
df1[numeric_columns] <- lapply(df1[numeric_columns], as.numeric) 


p1 <- df1 %>% 
  select(all_of(cat_keep)) %>%
  pivot_longer(cols=everything()) %>%
  ggplot(data=.) +
  geom_bar(aes(x=value), col="black", fill="white") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~name, scales="free", ncol=4)
p1
```

## Numerical Data

```{r, num_graphs, fig.height=20}

p2 <- df1 %>% 
  select(all_of(numeric_columns)) %>%
  pivot_longer(cols=everything()) %>%
  ggplot(data=.) +
  geom_boxplot(aes(y=value), col="black", fill="white") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~name, scales="free", ncol=4)
p2
```


